export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";
export const REMOVE_LOGIN_ERROR_MESSAGE = "REMOVE_LOGIN_ERROR_MESSAGE";

export const LOGOUT = "LOGOUT";
