export const mockQuizList = [
  {
    id: 1,
    topic: "Books and Authors - GK",
    isDeleted: false,
    questions: [
      {
        id: 1,
        question: "Who wrote the famous book 'We the people'?",
        options: [
          "T. N. Kaul",
          "J. R. D. Tata",
          "Khushwant Singh",
          "Nani Palkhivala",
        ],
        answer: "Nani Palkhivala",
        isDeleted: false,
      },
      {
        id: 2,
        question: "Who wrote the book 'Forbidden Verses'?",
        options: [
          "Salman Rushdie",
          "Abu Nuwas",
          "Ms. Taslima Nasrin",
          "D. H. Lawrence",
        ],
        answer: "Abu Nuwas",
        isDeleted: false,
      },
      {
        id: 3,
        question:
          "Who has written the book 'The frozen Turbulence in Kashmir'?",
        options: ["Anees Jung", "Jagmohan", "M. J. Akbar", "Nissim Ezekiel"],
        answer: "Jagmohan",
        isDeleted: false,
      },
      {
        id: 4,
        question: "In India first television programme is broadcasted in -",
        options: ["1959", "1965", "1950", "1943"],
        answer: "1959",
        isDeleted: false,
      },
      {
        id: 5,
        question: "'A Voice Of Freedom' is a book written by -",
        options: [
          "Corazon Aquino",
          "Nayantara Sahgal",
          "Aung San Suu Kyi",
          "Benazir Bhutto",
        ],
        answer: "Nayantara Sahgal",
        isDeleted: false,
      },
      {
        id: 6,
        question: "Who is the father of English poetry?",
        options: [
          "John Milton",
          "William Wordsworth",
          "Geoffrey Chaucer",
          "Charles Dickens",
        ],
        answer: "Geoffrey Chaucer",
        isDeleted: false,
      },
      {
        id: 7,
        question: "The famous book 'Anandmath' was authored by -",
        options: [
          "Sarojini Naidu",
          "Bankim Chandra Chattopadhyay",
          "Geoffrey Chaucer",
          "Charles Dickens",
        ],
        answer: "Bankim Chandra Chattopadhyay",
        isDeleted: false,
      },
      {
        id: 8,
        question:
          "Which of the following is a biography of the Lady Mountbatten?",
        options: [
          "Edwina Mountbatten - A Life of Her Own",
          "Edwina Mountbatten - Her relationship with Nehru",
          "Mountbatten",
          "Edwina Mountbattten",
        ],
        answer: "Edwina Mountbatten - A Life of Her Own",
        isDeleted: false,
      },
      {
        id: 9,
        question: "Who said 'God helps those who help themselves'?",
        options: [
          "Andre Maurois",
          "Andre Gide",
          "Algernon Sidney",
          "Father Discoste",
        ],
        answer: "Swami Vivekananda",
        isDeleted: false,
      },
      {
        id: 10,
        question:
          "'Alice in Wanderland' the famous tv serial is based on a book written by - ",
        options: [
          "Father Discoste",
          "Thomas Hardy",
          "Charles Dickens",
          "Lewis Caroll",
        ],
        answer: "Lewis Caroll",
        isDeleted: false,
      },
      {
        id: 11,
        question: "Who is the author of the book 'My Experiments with truth'?",
        options: [
          "Mahatma Gandhi",
          "Michael Anderson",
          "Winston Churchill",
          "Jarnes Morris",
        ],
        answer: "Mahatma Gandhi",
        isDeleted: false,
      },
    ],
  },
  {
    id: 2,
    topic: "Competetive English - Grammer",
    isDeleted: false,
    questions: [
      {
        id: 1,
        question: "Our sir teaches Mathematics ________ English.",
        options: ["besides", "beside", "both", "across"],
        answer: "besides",
        isDeleted: false,
      },
      {
        id: 2,
        question: "Please don't laugh ________ those beggars.",
        options: ["for", "against", "at", "from"],
        answer: "at",
        isDeleted: false,
      },
      {
        id: 3,
        question: "Please, stop ________ so many mistakes.",
        options: ["to make", "make", "making", "makes"],
        answer: "making",
        isDeleted: false,
      },
      {
        id: 4,
        question: "The rain come ________ the cloud.",
        options: ["in", "near", "from", "under"],
        answer: "from",
        isDeleted: false,
      },
      {
        id: 5,
        question: "The stars ________ counted.",
        options: ["can", "can be", "cannot be", "must"],
        answer: "cannot be",
        isDeleted: false,
      },
      {
        id: 6,
        question: "The Idiots ________ really a watchable movie.",
        options: ["are", "is", "superb", "do"],
        answer: "is",
        isDeleted: false,
      },
    ],
  },
  {
    id: 3,
    topic: "C Programming - C fundamentals",
    isDeleted: false,
    questions: [
      {
        id: 1,
        question: "Who is the father of C language",
        options: [
          "Bjarne Stroustrup",
          "James A. Gosling",
          "Dennis Ritchie",
          "Dr. E.F. Codd",
        ],
        answer: "Dennis Ritchie",
        isDeleted: false,
      },
      {
        id: 2,
        question: "C language developed at ________ ?",
        options: [
          "AT & T's Bell Laboratories of USA in 1972",
          "AT & T's Bell Laboratories of USA in 1970",
          "Sun Microsystems in 1973",
          "Cambridge University in 1972",
        ],
        answer: "AT & T's Bell Laboratories of USA in 1972",
        isDeleted: false,
      },
      {
        id: 3,
        question:
          "C programs are converted into machine language with the help of - ",
        options: [
          "An Editor",
          "A compiler",
          "An operating system",
          "None of these",
        ],
        answer: "A compiler",
        isDeleted: false,
      },
      {
        id: 4,
        question: "C was primarily developed as ",
        options: [
          "System programming language",
          "General purpose language",
          "Data processing language",
          "None of the above",
        ],
        answer: "System programming language",
        isDeleted: false,
      },
      {
        id: 5,
        question: "Standard ANCI C recognizes ______ number of keywords",
        options: ["30", "32", "36", "48"],
        answer: "32",
        isDeleted: false,
      },
    ],
  },
  {
    id: 4,
    topic: "Computer Science - Linux",
    isDeleted: false,
    questions: [
      {
        id: 1,
        question: "What command is used to remove file?",
        options: ["dm", "rm", "delete", "erase"],
        answer: "rm",
        isDeleted: false,
      },
      {
        id: 2,
        question: "What command is used to remove directory?",
        options: ["rdir", "remove", "rmdir", "None of these above"],
        answer: "rmdir",
        isDeleted: false,
      },
      {
        id: 3,
        question: "How many primary partitions can exist on one drive?",
        options: ["2", "4", "6", "None of these above"],
        answer: "4",
        isDeleted: false,
      },
      {
        id: 4,
        question: "What sign is used to back up over typing error?",
        options: ["!", "@", "#", "$"],
        answer: "#",
        isDeleted: false,
      },
    ],
  },
  {
    id: 5,
    topic: "General Science Questions",
    isDeleted: false,
    questions: [
      {
        id: 1,
        question: "What color does yellow and green make?",
        options: ["Lime", "Maroon", "Ocean mist", "Tangerine"],
        answer: "Lime",
        isDeleted: false,
      },
      {
        id: 2,
        question: "The blue colour of the clear sky is due to",
        options: [
          " Diffraction of light",
          "Dispersion of light",
          "Reflection of light",
          "Refraction of light",
        ],
        answer: "Dispersion of light",
        isDeleted: false,
      },
      {
        id: 3,
        question: "As you go down into a well, your weight",
        options: [
          "increases slightly",
          "decreases slightly",
          "remains exactly the same",
          "None of the above",
        ],
        answer: "decreases slightly",
        isDeleted: false,
      },
      {
        id: 4,
        question: "Which of the following is used in pencils?",
        options: ["Silicon", "Phosphorous", "Graphite", "Charcoal"],
        answer: "Graphite",
        isDeleted: false,
      },
      {
        id: 5,
        question:
          "The weight of an object will be minimum when it is placed at  ?",
        options: [
          "The North Pole",
          "The South Pole",
          "The Equator",
          "The center of the Earth",
        ],
        answer: "The center of the Earth",
        isDeleted: false,
      },
      {
        id: 6,
        question: "In fireworks, the green flame is produced because of",
        options: ["Sodium", "Potassium", "Barium", "Mercury"],
        answer: "Barium",
        isDeleted: false,
      },
      {
        id: 7,
        question: "What does airbag, used for safety of car driver, contain?",
        options: [
          "Sodium bicarbonate",
          "Sodium azide",
          "Sodium nitrite",
          "Sodium peroxide",
        ],
        answer: "Sodium azide",
        isDeleted: false,
      },
    ],
  },
];