export const QUIZ_LIST_REQUEST = "QUIZ_LIST_REQUEST";
export const QUIZ_LIST_REQUEST_SUCCESS = "QUIZ_LIST_REQUEST_SUCCESS";
export const QUIZ_LIST_REQUEST_FAILURE = "QUIZ_LIST_REQUEST_SUCCESS";

export const QUIZ_ADD_REQUEST = "QUIZ_ADD_REQUEST";
export const QUIZ_ADD_REQUEST_SUCCESS = "QUIZ_ADD_REQUEST_SUCCESS";
export const QUIZ_ADD_REQUEST_FAILURE = "QUIZ_ADD_REQUEST_FAILURE";

export const QUIZ_UPDATE_REQUEST = "QUIZ_UPDATE_REQUEST";
export const QUIZ_UPDATE_REQUEST_SUCCESS = "QUIZ_UPDATE_REQUEST_SUCCESS";
export const QUIZ_UPDATE_REQUEST_FAILURE = "QUIZ_UPDATE_REQUEST_FAILURE";

export const QUIZ_DELETE_REQUEST = "QUIZ_DELETE_REQUEST";
export const QUIZ_DELETE_REQUEST_SUCCESS = "QUIZ_DELETE_REQUEST_SUCCESS";
export const QUIZ_DELETE_REQUEST_FAILURE = "QUIZ_DELETE_REQUEST_FAILURE";

export const QUIZZES_ARCHIEVE_REQUEST = "QUIZZES_ARCHIEVE_REQUEST";
export const QUIZZES_ARCHIEVE_REQUEST_SUCCESS = "QUIZZES_ARCHIEVE_REQUEST_SUCCESS";
export const QUIZZES_ARCHIEVE_REQUEST_FAILURE = "QUIZZES_ARCHIEVE_REQUEST_FAILURE";

export const QUIZ_RESTORE_FROM_ARCHIEVE_REQUEST = "QUIZ_RESTORE_FROM_ARCHIEVE_REQUEST";
export const QUIZ_RESTORE_FROM_ARCHIEVE_REQUEST_SUCCESS =
  "QUIZ_RESTORE_FROM_ARCHIEVE_REQUEST_SUCCESS";
export const QUIZ_RESTORE_FROM_ARCHIEVE_REQUEST_FAILURE =
  "QUIZ_RESTORE_FROM_ARCHIEVE_REQUEST_FAILURE";

export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST";
export const ADD_QUESTION_REQUEST_SUCCESS = "ADD_QUESTION_REQUEST_SUCCESS";
export const ADD_QUESTION_REQUEST_FAILURE = "ADD_QUESTION_REQUEST_FAILURE";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_REQUEST_SUCCESS = "DELETE_QUESTION_REQUEST_SUCCESS";
export const DELETE_QUESTION_REQUEST_FAILURE = "DELETE_QUESTION_REQUEST_FAILURE";

export const REMOVE_QUIZ_ERROR_MESSAGE = "REMOVE_QUIZ_ERROR_MESSAGE";
export const REMOVE_QUIZ_UPDATE_MESAGE = "REMOVE_QUIZ_UPDATE_MESSAGE";
export const REMOVE_ADD_MESSAGE = "REMOVE_ADD_MESSAGE";
export const REMOVE_DELTE_MESSAGE = "REMOVE_DELETE_MESSAGE";